version: '3.1'
services:
  web:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/addons
    command: >
      odoo
      --db_host=db --db_port=5432 --db_user=odoo --db_password=odoo
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons
  db:
    image: postgres:15
    ports:
      - 5470:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  postgres_data:
