services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-odoo}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-odoo} -d ${POSTGRES_DB:-odoo}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:${ODOO_VERSION:-17.0}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8069:8069'
    command:
      - '--db_host=db'
      - '--db_user=${POSTGRES_USER:-odoo}'
      - '--db_password=${POSTGRES_PASSWORD:-odoo}'
      - '-d'
      - '${POSTGRES_DB:-odoo}'
    environment:
      # Optional timezone for logs; adjust as needed
      TZ: Asia/Jakarta
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons

volumes:
  db-data:
  odoo-data:
